In [1]:
import numpy as np

In [2]:
lst=[10,20,30,40]
arr=np.array(lst)
arr

array([10, 20, 30, 40])

In [3]:
lst=[1.5,5.4,2.5,3.6,4.5,5.9]
arr1=np.array(lst)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1=np.array([10,20,30],dtype=float) #int lai float ma change
arr1

array([10., 20., 30.])

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr1=np.array([10,20,30,-10,-20,0,0],dtype=bool) 
arr1

array([ True,  True,  True,  True,  True, False, False])

In [8]:
for i in range(1,20):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
np.arange(1,11) #1 to 10 samma array banara dinxa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,100,2) #1 1 step skip gardai

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# sum of elements in the list

In [11]:
l1=[10,20,30,40,50]
total=0 #product ma chai 1 rakhne
for element in l1:
    total=total+element
    

In [12]:
total

150

# Numpy ones and zeros

In [13]:
np.ones(4,dtype=int) #1d array 4 elements

array([1, 1, 1, 1])

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((3,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [16]:
np.ones((2,3,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [18]:
np.ones((2,2,4,3),dtype=int)

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

# numpy random arrays

In [19]:
np.random.random(2)  #2 ota random number generate, 0 to 1 ko bich ma dinxa

array([0.532748  , 0.47775389])

In [ ]:
np.random.random(2)*100 
#0 to 100 samma ko random dinxa, jati samma chaiyo teti le multiply

In [21]:
np.random.random((3,4))*50

array([[44.60372987, 43.34629569, 11.43085615, 32.8708842 ],
       [ 5.08619211, 36.78379306, 33.09428788, 28.97805751],
       [28.7993313 , 24.19514855, 26.86227237,  8.7246941 ]])

In [23]:
arr_4d=np.random.random((2,4,3,4))*50
arr_4d

array([[[[36.84071905, 28.0067252 , 18.25294312, 34.36657445],
         [ 4.80152185, 16.00945518, 45.48335935, 23.50103409],
         [11.37563004, 47.38951291, 14.35183255,  9.79019289]],

        [[31.41437732,  2.90380759, 12.71965123, 21.93692257],
         [39.90558124, 42.37594598, 18.10801938, 43.05541517],
         [48.22529818, 32.1574143 ,  0.34566679, 36.58307294]],

        [[38.83629508, 35.23541323, 33.2308281 ,  1.97571975],
         [28.92825621, 43.59731925, 35.28668833,  6.90524484],
         [13.16979682, 34.7751452 , 22.28486614, 12.13479322]],

        [[ 5.18376123, 27.68411982, 35.04794604,  3.52494877],
         [21.01782737,  1.30534351, 48.41738394, 16.97355347],
         [ 0.26391898, 24.82762051, 46.21391707,  6.85990157]]],


       [[[12.71811629, 30.09742798, 27.84173551, 26.92142681],
         [ 4.07884802, 42.59463692, 30.93101375, 36.44467299],
         [24.6111053 , 19.24639331, 13.17306847,  0.1746864 ]],

        [[41.37324572, 39.98496368, 24.8823

In [24]:
np.round(arr_4d,3) #round off to 3 digits after decimal

array([[[[36.841, 28.007, 18.253, 34.367],
         [ 4.802, 16.009, 45.483, 23.501],
         [11.376, 47.39 , 14.352,  9.79 ]],

        [[31.414,  2.904, 12.72 , 21.937],
         [39.906, 42.376, 18.108, 43.055],
         [48.225, 32.157,  0.346, 36.583]],

        [[38.836, 35.235, 33.231,  1.976],
         [28.928, 43.597, 35.287,  6.905],
         [13.17 , 34.775, 22.285, 12.135]],

        [[ 5.184, 27.684, 35.048,  3.525],
         [21.018,  1.305, 48.417, 16.974],
         [ 0.264, 24.828, 46.214,  6.86 ]]],


       [[[12.718, 30.097, 27.842, 26.921],
         [ 4.079, 42.595, 30.931, 36.445],
         [24.611, 19.246, 13.173,  0.175]],

        [[41.373, 39.985, 24.882, 24.379],
         [25.357, 12.733, 19.248, 20.436],
         [36.082, 32.155, 26.169, 49.874]],

        [[29.456, 34.4  , 45.991, 32.953],
         [ 5.904,  7.218, 19.415, 47.448],
         [25.995, 36.099,  4.846, 46.163]],

        [[33.558, 42.054, 28.714, 49.813],
         [32.629,  6.206, 17.282,  5.9

In [25]:
#20 to 30 samma ko random number
np.random.randint(20,50,10) #(start,end,katiota) #yo chai 1d ko lagi

array([46, 25, 38, 25, 23, 20, 45, 43, 26, 38], dtype=int32)

In [26]:
np.random.randint(20,50,size=(3,4)) #3*4 ko 2d chaiyeko vara

array([[48, 36, 49, 39],
       [22, 33, 34, 34],
       [36, 36, 20, 31]], dtype=int32)

In [27]:
np.random.randint(20,50,size=(3,3,4)) #3 ota 2d array

array([[[47, 43, 35, 31],
        [30, 39, 35, 24],
        [29, 31, 44, 49]],

       [[23, 43, 46, 20],
        [25, 36, 21, 40],
        [48, 22, 30, 40]],

       [[37, 38, 40, 35],
        [43, 34, 27, 28],
        [27, 31, 26, 34]]], dtype=int32)

# Reshape function in numpy

In [28]:
np.arange(10) #0 to 9, 10=total num of elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10).ndim

1

In [30]:
#convert to 2d
#5*2 and 2*5 possible for 10 elements
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.reshape(2,5) #2 row 5 column, can be also (5,2)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
np.arange(16)
#2*4*2,4*2*2,2*2*4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
np.arange(16).reshape(2,4,2) #(4,2) ko duita

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

# np.identity

In [39]:
np.identity(3,dtype=int) #3*3 ko identity matrix banauxa
#default datatype is float

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

# Multidimension array into 1d array ravel() and flatten()

In [42]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [43]:
mul_dim_arr=np.arange(16).reshape(4,2,2)
mul_dim_arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [44]:
mul_dim_arr.flatten() #1d array ma lanxa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
mul_dim_arr.ravel() #1d ma lanxa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
mul_dim_arr.ravel().reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])