# Addition program in python

### This is Sub heading

In [ ]:
#shift Enter= To execute the code
#esc+ m=to make the headings
#Double click d to delete the cells
#B to add new cells below
#A to add the cells on the above from the current cell
#restart the kernel=kernel>restart and run all cells

In [1]:
num1=int(input('Enter the number 1'))
num2=int(input('Enter the number 2'))
print(num1+num2)

Enter the number 1 2
Enter the number 2 3


5


In [2]:
num1
num2 #last cell matra display hunxa

3

In [3]:
print(num1)
num2 #esto garda chai duitai dekhinxa

2


3

# Numpy Fundamentals

In [16]:
l1=[10,20,30,40,50]
type(l1)


list

In [17]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [18]:
import numpy as np

In [20]:
arr=np.array(l1) #list to array convert
arr

array([10, 20, 30, 40, 50])

In [ ]:
#1d array= vector
#2d array= matrix
#3 or more=tensor

In [22]:
l2=[[10,20,21,22],[10,20,32,34],[34,56,32,12],[23,67,43,23]]
l2[1][1]

20

In [23]:
arr2d=np.array(l2)
arr2d

array([[10, 20, 21, 22],
       [10, 20, 32, 34],
       [34, 56, 32, 12],
       [23, 67, 43, 23]])

# arrays attributes

In [24]:
#size,shape,ndim
arr

array([10, 20, 30, 40, 50])

In [25]:
arr.shape #1d 

(5,)

In [26]:
arr2d.shape  #2d

(4, 4)

In [27]:
arr.size #no of elements

5

In [28]:
len(arr2d)

4

In [29]:
arr

array([10, 20, 30, 40, 50])

In [30]:
arr.ndim

1