### Create a 1D NumPy array

In [2]:
import numpy as np

In [4]:
arr1d=np.random.randint(1,10,5)
arr1d

array([2, 3, 3, 2, 6], dtype=int32)

In [8]:
arr1d.ndim

1

### Create a 2D numpy array

In [6]:
arr2d=np.random.randint(12,size=(3,4))
arr2d

array([[ 7,  5,  8,  1],
       [ 2,  1,  8,  4],
       [11,  5,  3,  6]], dtype=int32)

In [7]:
arr2d.ndim

2

### Create a 3D numpy array

In [9]:
arr3d=np.random.randint(12,size=(2,2,3))
arr3d

array([[[ 2,  2,  6],
        [11,  4,  7]],

       [[ 3,  8,  5],
        [ 4,  4, 11]]], dtype=int32)

In [10]:
arr3d.ndim

3

### Find the dimension of those arrays

In [11]:
arr1d.ndim

1

In [12]:
arr2d.ndim

2

In [13]:
arr3d.ndim

3

### Find total numbers of elements in a NumPy array

In [23]:
arr1d.size

5

In [15]:
len(arr1d)

5

In [22]:
arr2d.size

12

In [21]:
arr3d.size

12

### Change the data type of a numpy array

In [24]:
lst=[1.5,5.4,2.5,3.6,4.5,5.9]
arr=np.array(lst)
arr

array([1.5, 5.4, 2.5, 3.6, 4.5, 5.9])

In [25]:
arri=np.array(arr,dtype=int)
arri

array([1, 5, 2, 3, 4, 5])

### Create a 4*4 identity matrix with a boolean data type in NumPy

In [29]:
arr4=np.identity(4,dtype=bool)
arr4

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

### Generate a 4*5 matrix of ones in NumPy

In [32]:
arr5=np.ones((4,5),dtype=int)
arr5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Generate a 4*5 matrix of zeros in NumPy

In [33]:
arr5=np.zeros((4,5),dtype=int)
arr5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Generate a random numpy array between 1 to 500 of size 4*5

In [36]:
array=np.random.random(4*5)*500
array

array([ 34.3245989 , 295.5145268 ,  26.6177256 , 473.1492195 ,
       131.45842207, 273.27054355, 415.10319906, 430.82125014,
       171.1714662 , 467.97412226, 217.93395928, 263.31708259,
       105.178112  , 244.6967637 ,  28.03686475, 385.36465059,
       152.60109635, 230.52957322, 474.11815047, 167.8914646 ])