In [2]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92],
      dtype=int32)

# np.sort()

In [3]:
#np.sort() : sorts array asc or desc
np.sort(a) #asc

array([ 8, 16, 18, 29, 32, 40, 40, 42, 44, 53, 58, 60, 60, 85, 92],
      dtype=int32)

In [4]:
np.sort(a)[::-1]#desc

array([92, 85, 60, 60, 58, 53, 44, 42, 40, 40, 32, 29, 18, 16,  8],
      dtype=int32)

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 46, 81, 97],
       [84, 16, 31, 56],
       [22, 83, 27, 75],
       [33, 16, 66, 31],
       [21, 22, 70, 85],
       [92, 64, 34, 66]], dtype=int32)

In [6]:
#sorting row wise and column wise
np.sort(b,axis=0)#column wise

array([[21, 16, 27, 31],
       [22, 16, 31, 56],
       [33, 22, 34, 66],
       [34, 46, 66, 75],
       [84, 64, 70, 85],
       [92, 83, 81, 97]], dtype=int32)

In [7]:
np.sort(b,axis=1) #row wise

array([[34, 46, 81, 97],
       [16, 31, 56, 84],
       [22, 27, 75, 83],
       [16, 31, 33, 66],
       [21, 22, 70, 85],
       [34, 64, 66, 92]], dtype=int32)

# flatten and revel

In [8]:
b.ravel() #1D banxa

array([34, 46, 81, 97, 84, 16, 31, 56, 22, 83, 27, 75, 33, 16, 66, 31, 21,
       22, 70, 85, 92, 64, 34, 66], dtype=int32)

In [9]:
b.flatten() #1D banxa

array([34, 46, 81, 97, 84, 16, 31, 56, 22, 83, 27, 75, 33, 16, 66, 31, 21,
       22, 70, 85, 92, 64, 34, 66], dtype=int32)

# append

In [10]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92],
      dtype=int32)

In [11]:
#adding 10 to the array
np.append(a,10) #last ma add hunxa,temporarily add hunxa
#original array ma add hunna

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10])

In [13]:
#permanent banauna lai:
a=np.append(a,10)
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

# Concatenate

In [17]:
c=np.arange(1,7).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.concatenate((c,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d,c,d,c))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [21]:
np.concatenate((c,d),axis=1) 

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [22]:
merged_array=np.concatenate((c,d))
merged_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# unique

In [24]:
arr=np.array([10,20,10,30,20,10,10,50,60,90,90])
arr

array([10, 20, 10, 30, 20, 10, 10, 50, 60, 90, 90])

In [25]:
np.unique(arr) #gives unique element without repetition

array([10, 20, 30, 50, 60, 90])

In [26]:
arr.shape

(11,)

# expand dimension

In [27]:
np.expand_dims(arr,axis=0)

array([[10, 20, 10, 30, 20, 10, 10, 50, 60, 90, 90]])

In [28]:
np.expand_dims(arr,axis=1)

array([[10],
       [20],
       [10],
       [30],
       [20],
       [10],
       [10],
       [50],
       [60],
       [90],
       [90]])

# where

In [29]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [30]:
a.size

17

In [31]:
#>50 extracting
#np.where(condition,true,false)
np.where(a>50) #gives index postion of >50 elements

(array([ 0,  3,  7, 11, 12, 14]),)

In [32]:
type(np.where(a>50))

tuple

In [33]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [34]:
#odd numbers ko index pos
np.where(a%2==0)

(array([ 0,  2,  3,  4,  5,  6,  8,  9, 10, 11, 13, 14, 15, 16]),)

In [35]:
#replacing even with 'even' and odd with 'odd'
np.where(a%2==0,'even','odd')#np.where(condition,true,false)

array(['even', 'odd', 'even', 'even', 'even', 'even', 'even', 'odd',
       'even', 'even', 'even', 'even', 'odd', 'even', 'even', 'even',
       'even'], dtype='<U4')

In [36]:
np.where(a%2==0,a+10,a) #even vaye 10 add natra same

array([ 70,  29,  50,  68,  42,  26,  54,  85,  50,  28,  52,  70,  53,
        18, 102,  20,  20])

In [37]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

# transpose

In [38]:
arr2d=np.random.randint(1,100,size=(3,4))
arr2d

array([[ 1, 46, 75, 21],
       [77, 45,  9, 28],
       [73, 18, 27, 96]], dtype=int32)

In [39]:
#row change to column and viceverse
np.transpose(arr2d)

array([[ 1, 77, 73],
       [46, 45, 18],
       [75,  9, 27],
       [21, 28, 96]], dtype=int32)

In [40]:
arr2d.T #next method

array([[ 1, 77, 73],
       [46, 45, 18],
       [75,  9, 27],
       [21, 28, 96]], dtype=int32)

# argmax,argmin

In [42]:
arr2d

array([[ 1, 46, 75, 21],
       [77, 45,  9, 28],
       [73, 18, 27, 96]], dtype=int32)

In [44]:
np.argmin(arr2d,axis=0) #column wise min index position

array([0, 2, 1, 0])

In [45]:
np.argmin(arr2d,axis=1) #row wise

array([0, 2, 1])

In [ ]:
#same for minimum

# cumulative sum

In [46]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [ ]:
#cumulative addition
# 20-20
# 30-50
# 40-90

In [47]:
np.cumsum(a)

array([ 60,  89, 129, 187, 219, 235, 279, 364, 404, 422, 464, 524, 577,
       585, 677, 687, 697])

In [48]:
arr

array([10, 20, 10, 30, 20, 10, 10, 50, 60, 90, 90])

In [49]:
arr=np.cumsum(a)
arr

array([ 60,  89, 129, 187, 219, 235, 279, 364, 404, 422, 464, 524, 577,
       585, 677, 687, 697])

In [50]:
np.where(arr>500) #gives indexing

(array([11, 12, 13, 14, 15, 16]),)

In [51]:
np.where(arr>500)[0]

array([11, 12, 13, 14, 15, 16])

In [52]:
int(np.where(arr>500)[0][0]) #11th day ma greater than 500 vako raixa

11

In [53]:
arr2d

array([[ 1, 46, 75, 21],
       [77, 45,  9, 28],
       [73, 18, 27, 96]], dtype=int32)

In [54]:
np.cumsum(arr2d,axis=0) #columnwise

array([[  1,  46,  75,  21],
       [ 78,  91,  84,  49],
       [151, 109, 111, 145]])

In [55]:
np.cumsum(arr2d,axis=1) #row wise

array([[  1,  47, 122, 143],
       [ 77, 122, 131, 159],
       [ 73,  91, 118, 214]])

In [56]:
np.cumprod(a) #64 bit vanda dherai vara -minus ma random num aako

array([                  60,                 1740,                69600,
                    4036800,            129177600,           2066841600,
                90941030400,        7729987584000,      309199503360000,
           5565591060480000,   233754824540160000, -4421454601299951616,
        5470579089326735360,  6871144567194779648,  4956001675794972672,
       -5780215463178928128, -2461922410660626432])

# percentiles

In [57]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [58]:
np.percentile(a,10)

np.float64(10.0)

In [59]:
np.sort(a)

array([ 8, 10, 10, 16, 18, 29, 32, 40, 40, 42, 44, 53, 58, 60, 60, 85, 92])

In [60]:
np.percentile(a,10) #10% data k vanda tala xa?
#10 aayo so 10 vanda tala 10% data xa

np.float64(10.0)

In [61]:
np.percentile(a,50)

np.float64(40.0)

In [62]:
np.median(a) #same as 50 percentile

np.float64(40.0)

# histograms

In [63]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [ ]:
#let those are ages
#0-10(kid),11-20(children),21-30(adult)>>bins

In [65]:
np.histogram(a,[0,10,30,40])

(array([1, 5, 3]), array([ 0, 10, 30, 40]))

# np.isin()

In [68]:
item=[10,20,30,12]

In [69]:
a

array([60, 29, 40, 58, 32, 16, 44, 85, 40, 18, 42, 60, 53,  8, 92, 10, 10])

In [70]:
np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True])

In [71]:
a[np.isin(a,item)]

array([10, 10])

In [72]:
np.flip(a) #reverse

array([10, 10, 92,  8, 53, 60, 42, 18, 40, 85, 44, 16, 32, 58, 40, 29, 60])

# put()

In [74]:
np.put(a,[0,1,4],[100,200,300]) #(kun array, kun index, tyo inex ma k)

In [75]:
a #put does permanent change in original array

array([100, 200,  40,  58, 300,  16,  44,  85,  40,  18,  42,  60,  53,
         8,  92,  10,  10])

# delete()

In [76]:
np.delete(a,[0,1,3]) #original bata faldena , falna ko lagi reassign

array([ 40, 300,  16,  44,  85,  40,  18,  42,  60,  53,   8,  92,  10,
        10])

# tolist()

In [77]:
a.tolist() #array to list

[100, 200, 40, 58, 300, 16, 44, 85, 40, 18, 42, 60, 53, 8, 92, 10, 10]

In [78]:
np.array(a.tolist())

array([100, 200,  40,  58, 300,  16,  44,  85,  40,  18,  42,  60,  53,
         8,  92,  10,  10])