In [1]:
import numpy as np

In [10]:
arr1=np.arange(4).reshape(2,2)
arr1

array([[0, 1],
       [2, 3]])

In [11]:
arr2=np.arange(4,8).reshape(2,2)
arr2

array([[4, 5],
       [6, 7]])

# Vector operations

In [13]:
arr3=arr1+arr2
arr3
#likewise addition, sub, mult, div, modulo

array([[ 4,  6],
       [ 8, 10]])

# scalar operations

In [16]:
arr1=np.array([10,20,30,40,50,60])
arr1

array([10, 20, 30, 40, 50, 60])

In [18]:
arr1+10 #sabai ma 10 add

array([20, 30, 40, 50, 60, 70])

In [19]:
arr1**2 #sabai ma power 2

array([ 100,  400,  900, 1600, 2500, 3600])

In [23]:
arr2d=np.arange(12).reshape(3,4)+10
arr2d

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [24]:
arr2d%2==1 #1 aauni m atrue aru ma false

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [25]:
arr2d[arr2d%2==1]

array([11, 13, 15, 17, 19, 21])

# Relational operators in numpy arrays

In [29]:
random_array=np.random.randint(0,100,9).reshape(3,3)
random_array

array([[73, 21, 84],
       [76, 88, 23],
       [44,  6, 38]], dtype=int32)

In [31]:
random_array==6

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [32]:
random_array[random_array==6]

array([6], dtype=int32)

In [33]:
random_array[random_array==6].size

1

In [35]:
len(random_array[random_array==6])

1

In [36]:
random_array >50

array([[ True, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [37]:
random_array[random_array >50]

array([73, 84, 76, 88], dtype=int32)

In [38]:
~(random_array==6) #6 ko thaau ma false

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [40]:
random_array[~(random_array ==6)]

array([73, 21, 84, 76, 88, 23, 44, 38], dtype=int32)

In [41]:
random_array=np.random.randint(0,100,12).reshape(4,3)
random_array

array([[80, 72, 61],
       [14, 46, 22],
       [31, 74, 28],
       [11, 62, 70]], dtype=int32)

# Logic gates

In [42]:
random_array

array([[80, 72, 61],
       [14, 46, 22],
       [31, 74, 28],
       [11, 62, 70]], dtype=int32)

In [43]:
random_array%3==0 #array divisible by 3

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
random_array%5==0

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [45]:
(random_array%3==0) & (random_array%5==0) #and

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [46]:
random_array[(random_array%3==0) & (random_array%5==0)]

array([], dtype=int32)

In [47]:
(random_array%3==0) | (random_array%5==0) #or

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [48]:
random_array[(random_array%3==0) | (random_array%5==0)]

array([80, 72, 70], dtype=int32)

In [49]:
random_array[~((random_array%3==0) | (random_array%5==0))] #not 

array([61, 14, 46, 22, 31, 74, 28, 11, 62], dtype=int32)

# aggregate functions in an array(min, max,sum,prod,mean,std,var)

In [51]:
arr2d=np.random.randint(1,100,16).reshape(4,4)
arr2d

array([[67, 47, 64,  1],
       [76, 66, 67,  7],
       [ 6, 29, 24, 31],
       [33, 60, 52,  1]], dtype=int32)

In [53]:
int(np.min(arr2d)) #extracts sabse sano from the array

1

In [54]:
np.min(arr2d)

np.int32(1)

In [55]:
np.min(arr2d,axis=0) #columnwise herxa axis=0 rakhda

array([ 6, 29, 24,  1], dtype=int32)

In [56]:
np.min(arr2d,axis=1) #row wise herxa axis=1 rakhda

array([1, 7, 6, 1], dtype=int32)

## average, mean

In [57]:
arr2d

array([[67, 47, 64,  1],
       [76, 66, 67,  7],
       [ 6, 29, 24, 31],
       [33, 60, 52,  1]], dtype=int32)

In [58]:
np.mean(arr2d) #whole ko mean

np.float64(39.4375)

In [59]:
np.sum(arr2d)

np.int64(631)

In [62]:
np.mean(arr2d,axis=0) #column wise ko mean

array([45.5 , 50.5 , 51.75, 10.  ])

In [63]:
np.mean(arr2d,axis=1) #row wise ko mean


array([44.75, 54.  , 22.5 , 36.5 ])

In [64]:
np.prod(arr2d)

np.int64(-7864108208109518848)

In [65]:
arr2d[1]

array([76, 66, 67,  7], dtype=int32)

In [66]:
np.mean(arr2d[1])

np.float64(54.0)

# traverse the elements in the array

In [67]:
arr2d

array([[67, 47, 64,  1],
       [76, 66, 67,  7],
       [ 6, 29, 24, 31],
       [33, 60, 52,  1]], dtype=int32)

In [68]:
len(arr2d)

4

In [70]:
for array in arr2d:
    print(array)
    print('*'*30)

[67 47 64  1]
******************************
[76 66 67  7]
******************************
[ 6 29 24 31]
******************************
[33 60 52  1]
******************************


In [71]:
for array in arr2d:
    for element in array:
        print(element)

67
47
64
1
76
66
67
7
6
29
24
31
33
60
52
1


# np.diter()

In [72]:
arr2d

array([[67, 47, 64,  1],
       [76, 66, 67,  7],
       [ 6, 29, 24, 31],
       [33, 60, 52,  1]], dtype=int32)

In [74]:
for element in np.nditer(arr2d):
    print(element)

67
47
64
1
76
66
67
7
6
29
24
31
33
60
52
1


In [76]:
arr4d=np.random.randint(1,100,size=(4,3,2,2))
arr4d

array([[[[71, 83],
         [70,  8]],

        [[80,  1],
         [34, 32]],

        [[88, 71],
         [37, 39]]],


       [[[33,  1],
         [42,  1]],

        [[54, 35],
         [80, 53]],

        [[62, 54],
         [ 1, 11]]],


       [[[ 9, 52],
         [27, 89]],

        [[ 7, 36],
         [ 6, 27]],

        [[53, 80],
         [24, 80]]],


       [[[94, 74],
         [16, 13]],

        [[70, 99],
         [28, 14]],

        [[ 5, 85],
         [10, 94]]]], dtype=int32)

In [77]:
for i in arr4d:
    print(i)
    print('_'*30)

[[[71 83]
  [70  8]]

 [[80  1]
  [34 32]]

 [[88 71]
  [37 39]]]
______________________________
[[[33  1]
  [42  1]]

 [[54 35]
  [80 53]]

 [[62 54]
  [ 1 11]]]
______________________________
[[[ 9 52]
  [27 89]]

 [[ 7 36]
  [ 6 27]]

 [[53 80]
  [24 80]]]
______________________________
[[[94 74]
  [16 13]]

 [[70 99]
  [28 14]]

 [[ 5 85]
  [10 94]]]
______________________________
